version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Cyanic76"
    commit-message:
      prefix: "Actions update"
    target-branch: "main"
