pipeline:
  build:
    image: alpine/git
    environment:
      # Information that will be used when authoring a commit
      - GIT_AUTHOR_NAME=Layers
      - GIT_AUTHOR_EMAIL=layers@noreply.codeberg.org
      - GIT_COMMIT_MESSAGE=Merging hosts files together
      # Basic repo information
      - GITEA_HOST=codeberg.org
      - GITEA_REPOSITORY=Cyanic76/Hosts
      - GITEA_BRANCH=pages
    secrets: [ gitea_token ]
    commands:
      # Setup git and checkout pages
      - git clone https://codeberg.org/Cyanic76/Hosts
      - git config --global user.name "$${GIT_AUTHOR_NAME}"
      - git config --global user.email "$${GIT_AUTHOR_EMAIL}"
      - git checkout "$${GITEA_BRANCH}"
      # Merge everything together and add the header
      - cd Hosts
      - cat cyanicHosts.txt | grep -E '^0.0.0.0.*$' >> allhosts.txt
      - cat kind/* | grep -E '^0.0.0.0.*$' >> allhosts.txt
      - cd corporations && find . -type f -exec cat {} + >> ../allhosts.txt
      - cd ..
      - sed '/^!/d' < allhosts.txt > allhosts.txt
      - cat assets/allhosts_template.txt >> allhosts.txt
      # Commit the file
      - git add allhosts.txt
      - git commit -m "$${GIT_COMMIT_MESSAGE} [ci skip]"
      - git remote set-url origin "https://Cyanic76:$${GITEA_TOKEN}@$${GITEA_HOST}/$${GITEA_REPOSITORY}.git"
      - git push origin "$${GITEA_BRANCH}"
    when:
      branch: pages
      path:
        include: [ 'cyanicHosts.txt', 'corporations/*.txt', 'corporations/*/*.txt', 'kind/*.txt' ]
        exclude: [ 'LICENSE*', '*.md', 'index.html', 'assets/*', 'kind/unknown.txt' ]
