steps:
  build:
    image: alpine
    environment:
      # Information that will be used when authoring a commit
      - GIT_AUTHOR_NAME=Layers
      - GIT_AUTHOR_EMAIL=layers@noreply.codeberg.org
      - GIT_COMMIT_MESSAGE=All hosts
      # Basic repo information
      - GITEA_HOST=codeberg.org
      - GITEA_REPOSITORY=Cyanic76/Hosts
      - GITEA_BRANCH=pages
    commands:
      - apk add git
      - git clone https://codeberg.org/Cyanic76/Hosts
      - git config --global user.name "$${GIT_AUTHOR_NAME}"
      - git config --global user.email "$${GIT_AUTHOR_EMAIL}"
      - git checkout "$${GITEA_BRANCH}"
      - cd Hosts
      - cat cyanicHosts.txt | grep -E '^0.0.0.0.*$' >> allhosts.txt && echo "1"
      - cat kind/* | grep -E '^0.0.0.0.*$' >> allhosts.txt && echo "2"
      - cd corporations && find . -type f -exec cat {} + >> ../allhosts.txt && echo "3"
      - cd ..
      #- sed '/^!/d' < allhosts.txt > allhosts.txt && echo "4"
      #- cat assets/allhosts_template.txt >> allhosts.txt && echo "5"
      - git add allhosts.txt -v
      - git commit -vm "$${GIT_COMMIT_MESSAGE} [ci skip]"
      - git remote set-url origin "https://Cyanic76:$${GITEA_TOKEN}@$${GITEA_HOST}/$${GITEA_REPOSITORY}.git"
      - git push origin "$${GITEA_BRANCH}"
    secrets: [ gitea_token ]
    when:
      branch: pages
      path:
        include: [ 'cyanicHosts.txt', 'corporations/*.txt', 'corporations/*/*.txt', 'kind/*.txt' ]
        exclude: [ 'LICENSE*', '*.md', 'index.html', 'assets/*', 'kind/unknown.txt' ]
