name: Merge all files into one

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - workflow

jobs:
  merge-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          submodules: true
      - name: Add main files
        run: cat cyanicHosts.txt | grep -E '^0.0.0.0.*$' >> hosts.txt
      - name: Add other files
        run: cat corporations/* | grep -E '^0.0.0.0.*$' >> hosts.txt
      - name: Upload large file
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: hosts.txt
          retention-days: 5
        
